/**
 * The TypeScript core must reproduce the Python generator (current-density
 * `molgen`) for every fixture: same atom count, same order, same coordinates.
 *
 * With orient = 'none' the comparison is exact, row by row. With
 * orient = 'principal' a molecule whose skew vanishes (symmetric under x -> -x)
 * may legitimately come back rotated by 180 degrees, because numpy's eigh does not
 * promise an eigenvector sign; the test accepts either, but nothing else.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildMolecule, parseXyz, toXyz } from '../src/core';

const dir = join(__dirname, 'fixtures');
const manifest = JSON.parse(readFileSync(join(dir, 'manifest.json'), 'utf8')) as Record<
  string,
  { cells: [number, number][]; formula: string }
>;

function rows(text: string) {
  return parseXyz(text).atoms;
}

describe('fixtures generated by the Python molgen', () => {
  for (const [name, { cells, formula }] of Object.entries(manifest)) {
    it(`${name} (${formula}) matches with orient=none, byte for byte`, () => {
      const expected = readFileSync(join(dir, `${name}.none.xyz`), 'utf8');
      const m = buildMolecule(cells, { orient: 'none' });
      expect(m.formula).toBe(formula);
      const actual = toXyz(m);
      // Compare numerically first for a readable failure, then byte-for-byte.
      const a = rows(actual);
      const e = rows(expected);
      expect(a.length).toBe(e.length);
      a.forEach((row, i) => {
        expect(row.Z).toBe(e[i].Z);
        expect(row.x).toBeCloseTo(e[i].x, 6);
        expect(row.y).toBeCloseTo(e[i].y, 6);
        expect(row.z).toBeCloseTo(e[i].z, 6);
      });
      expect(actual.replace(/-0\.000000/g, '0.000000')).toBe(
        expected.replace(/-0\.000000/g, '0.000000'),
      );
    });

    it(`${name} (${formula}) matches with orient=principal, up to a 180-degree turn`, () => {
      const expected = rows(readFileSync(join(dir, `${name}.principal.xyz`), 'utf8'));
      const actual = rows(toXyz(buildMolecule(cells, { orient: 'principal' })));
      expect(actual.length).toBe(expected.length);
      const same = actual.every(
        (r, i) => Math.abs(r.x - expected[i].x) < 1e-5 && Math.abs(r.y - expected[i].y) < 1e-5,
      );
      const flipped = actual.every(
        (r, i) => Math.abs(r.x + expected[i].x) < 1e-5 && Math.abs(r.y + expected[i].y) < 1e-5,
      );
      expect(same || flipped).toBe(true);
      actual.forEach((r, i) => expect(r.Z).toBe(expected[i].Z));
    });
  }
});
