/**
 * Named molecules. The cell lists were extracted from the DFT geometries of the
 * current-density dataset by `molgen/audit.py`; `aliases` are the names that
 * generator accepts, so the two tools agree on every preset.
 */
import type { Cell } from './types';

export interface Preset {
  id: string;
  name: string;
  formula: string;
  description: string;
  /** Names accepted by the current-density molgen API for the same molecule. */
  aliases: string[];
  cells: Cell[];
}

export const PRESETS: readonly Preset[] = [
  {
    id: 'benzene',
    name: 'Benzene',
    formula: 'C6H6',
    description: 'The single ring.',
    aliases: ['benzene', 'train_1', 'test_benz'],
    cells: [[0, 0]],
  },
  {
    id: 'naphthalene',
    name: 'Naphthalene',
    formula: 'C10H8',
    description: 'Two fused rings.',
    aliases: ['naphthalene', 'train_2'],
    cells: [
      [0, 0],
      [1, 0],
    ],
  },
  {
    id: 'anthracene',
    name: 'Anthracene',
    formula: 'C14H10',
    description: 'Three rings in a line (acene, n = 3).',
    aliases: ['anthracene', 'train_3'],
    cells: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
  },
  {
    id: 'tetracene',
    name: 'Tetracene',
    formula: 'C18H12',
    description: 'Four rings in a line (acene, n = 4).',
    aliases: ['tetracene', 'train_4'],
    cells: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
    ],
  },
  {
    id: 'phenanthrene',
    name: 'Phenanthrene',
    formula: 'C14H10',
    description: 'Three rings, angular; has one bay region.',
    aliases: ['phenanthrene', 'train_5'],
    cells: [
      [0, 1],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'chrysene',
    name: 'Chrysene',
    formula: 'C18H12',
    description: 'Four rings, zigzag (angular chain, n = 4).',
    aliases: ['train_7'],
    cells: [
      [0, 1],
      [1, 1],
      [2, 0],
      [3, 0],
    ],
  },
  {
    id: 'tetraphene',
    name: 'Tetraphene',
    formula: 'C18H12',
    description: 'Benz[a]anthracene: anthracene with one angular ring.',
    aliases: ['train_8'],
    cells: [
      [0, 1],
      [1, 1],
      [2, 1],
      [3, 0],
    ],
  },
  {
    id: 'pyrene',
    name: 'Pyrene',
    formula: 'C16H10',
    description: 'Four rings in a compact 2 x 2 block.',
    aliases: ['pyrene', 'train_6'],
    cells: [
      [0, 1],
      [1, 0],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'triphenylene',
    name: 'Triphenylene',
    formula: 'C18H12',
    description: 'Three rings around a central one; round (no long axis).',
    aliases: ['triphenylene', 'train_9'],
    cells: [
      [0, 2],
      [1, 0],
      [1, 1],
      [2, 1],
    ],
  },
  {
    id: 'perylene',
    name: 'Perylene',
    formula: 'C20H12',
    description: 'Two naphthalene units joined by a central ring.',
    aliases: ['perylene', 'test_perilen'],
    cells: [
      [0, 1],
      [0, 2],
      [1, 1],
      [2, 0],
      [2, 1],
    ],
  },
  {
    id: 'coronene',
    name: 'Coronene',
    formula: 'C24H12',
    description: 'Six rings around a central one (hexagonal flake, radius 1).',
    aliases: ['coronene', 'train_11', 'test_koronen'],
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 1],
    ],
  },
  {
    id: 'hbc',
    name: 'Hexabenzocoronene',
    formula: 'C42H18',
    description: 'Coronene with six extra rings (C42H18).',
    aliases: ['hbc', 'test_HBC'],
    cells: [
      [0, 3],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 1],
      [2, 2],
      [2, 3],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [4, 1],
    ],
  },
  {
    id: 'dataset-10',
    name: 'Dibenzopyrene (dataset #10)',
    formula: 'C24H14',
    description: 'Pyrene with two extra rings on opposite ends.',
    aliases: ['train_10'],
    cells: [
      [0, 3],
      [1, 1],
      [1, 2],
      [2, 1],
      [2, 2],
      [3, 0],
    ],
  },
  {
    id: 'dataset-14',
    name: 'C84H30 flake (dataset #14)',
    formula: 'C84H30',
    description: '28-ring graphene-like flake from the training set.',
    aliases: ['train_14'],
    cells: [
      [0, 7],
      [1, 5],
      [1, 6],
      [1, 7],
      [1, 8],
      [2, 5],
      [2, 6],
      [2, 7],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [4, 4],
      [4, 5],
      [5, 3],
      [5, 4],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [7, 1],
      [7, 2],
      [7, 3],
      [8, 0],
      [8, 1],
      [8, 2],
      [8, 3],
      [9, 1],
    ],
  },
  {
    id: 'dataset-15',
    name: 'C96H30 flake (dataset #15)',
    formula: 'C96H30',
    description: '34-ring graphene-like flake from the training set.',
    aliases: ['train_15'],
    cells: [
      [0, 6],
      [1, 4],
      [1, 5],
      [1, 6],
      [1, 7],
      [2, 4],
      [2, 5],
      [2, 6],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [4, 6],
      [4, 7],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [6, 0],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
      [6, 6],
      [7, 1],
      [7, 4],
    ],
  },
  {
    id: 'dataset-12',
    name: 'C114H30 flake (dataset #12)',
    formula: 'C114H30',
    description: '43-ring flake; the largest training molecule (144 atoms).',
    aliases: ['train_12'],
    cells: [
      [0, 6],
      [1, 4],
      [1, 5],
      [1, 6],
      [1, 7],
      [2, 2],
      [2, 3],
      [2, 4],
      [2, 5],
      [2, 6],
      [2, 7],
      [2, 8],
      [3, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [4, 6],
      [4, 7],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [6, 0],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
      [6, 6],
      [7, 1],
      [7, 2],
      [7, 3],
      [7, 4],
      [8, 2],
    ],
  },
];

export function presetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
