/**
 * Named molecules. The cell lists were extracted from DFT-optimised geometries by
 * detecting the hexagonal rings in each structure.
 */
import type { Cell } from './types';

export interface Preset {
  id: string;
  name: string;
  formula: string;
  description: string;
  cells: Cell[];
}

export const PRESETS: readonly Preset[] = [
  {
    id: 'benzene',
    name: 'Benzene',
    formula: 'C6H6',
    description: 'The single ring.',
    cells: [[0, 0]],
  },
  {
    id: 'naphthalene',
    name: 'Naphthalene',
    formula: 'C10H8',
    description: 'Two fused rings.',
    cells: [
      [0, 0],
      [1, 0],
    ],
  },
  {
    id: 'anthracene',
    name: 'Anthracene',
    formula: 'C14H10',
    description: 'Three rings in a line (acene, n = 3).',
    cells: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
  },
  {
    id: 'tetracene',
    name: 'Tetracene',
    formula: 'C18H12',
    description: 'Four rings in a line (acene, n = 4).',
    cells: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
    ],
  },
  {
    id: 'phenanthrene',
    name: 'Phenanthrene',
    formula: 'C14H10',
    description: 'Three rings, angular; has one bay region.',
    cells: [
      [0, 1],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'chrysene',
    name: 'Chrysene',
    formula: 'C18H12',
    description: 'Four rings, zigzag (angular chain, n = 4).',
    cells: [
      [0, 1],
      [1, 1],
      [2, 0],
      [3, 0],
    ],
  },
  {
    id: 'tetraphene',
    name: 'Tetraphene',
    formula: 'C18H12',
    description: 'Benz[a]anthracene: anthracene with one angular ring.',
    cells: [
      [0, 1],
      [1, 1],
      [2, 1],
      [3, 0],
    ],
  },
  {
    id: 'pyrene',
    name: 'Pyrene',
    formula: 'C16H10',
    description: 'Four rings in a compact 2 x 2 block.',
    cells: [
      [0, 1],
      [1, 0],
      [1, 1],
      [2, 0],
    ],
  },
  {
    id: 'triphenylene',
    name: 'Triphenylene',
    formula: 'C18H12',
    description: 'Three rings around a central one; round (no long axis).',
    cells: [
      [0, 2],
      [1, 0],
      [1, 1],
      [2, 1],
    ],
  },
  {
    id: 'perylene',
    name: 'Perylene',
    formula: 'C20H12',
    description: 'Two naphthalene units joined by a central ring.',
    cells: [
      [0, 1],
      [0, 2],
      [1, 1],
      [2, 0],
      [2, 1],
    ],
  },
  {
    id: 'coronene',
    name: 'Coronene',
    formula: 'C24H12',
    description: 'Six rings around a central one (hexagonal flake, radius 1).',
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, 0],
      [2, 1],
    ],
  },
  {
    id: 'hbc',
    name: 'Hexabenzocoronene',
    formula: 'C42H18',
    description: 'Coronene with six extra rings (C42H18).',
    cells: [
      [0, 3],
      [1, 1],
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 1],
      [2, 2],
      [2, 3],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [4, 1],
    ],
  },
  {
    id: 'dibenzopyrene',
    name: 'Dibenzopyrene',
    formula: 'C24H14',
    description: 'Pyrene with two extra rings on opposite ends.',
    cells: [
      [0, 3],
      [1, 1],
      [1, 2],
      [2, 1],
      [2, 2],
      [3, 0],
    ],
  },
  {
    id: 'flake-84',
    name: 'C84H30 flake',
    formula: 'C84H30',
    description: '28-ring graphene-like flake.',
    cells: [
      [0, 7],
      [1, 5],
      [1, 6],
      [1, 7],
      [1, 8],
      [2, 5],
      [2, 6],
      [2, 7],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [4, 4],
      [4, 5],
      [5, 3],
      [5, 4],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [7, 1],
      [7, 2],
      [7, 3],
      [8, 0],
      [8, 1],
      [8, 2],
      [8, 3],
      [9, 1],
    ],
  },
  {
    id: 'flake-96',
    name: 'C96H30 flake',
    formula: 'C96H30',
    description: '34-ring graphene-like flake.',
    cells: [
      [0, 6],
      [1, 4],
      [1, 5],
      [1, 6],
      [1, 7],
      [2, 4],
      [2, 5],
      [2, 6],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [4, 6],
      [4, 7],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [6, 0],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
      [6, 6],
      [7, 1],
      [7, 4],
    ],
  },
  {
    id: 'flake-114',
    name: 'C114H30 flake',
    formula: 'C114H30',
    description: '43-ring graphene-like flake (144 atoms).',
    cells: [
      [0, 6],
      [1, 4],
      [1, 5],
      [1, 6],
      [1, 7],
      [2, 2],
      [2, 3],
      [2, 4],
      [2, 5],
      [2, 6],
      [2, 7],
      [2, 8],
      [3, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [4, 1],
      [4, 2],
      [4, 3],
      [4, 4],
      [4, 5],
      [4, 6],
      [4, 7],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [6, 0],
      [6, 1],
      [6, 2],
      [6, 3],
      [6, 4],
      [6, 5],
      [6, 6],
      [7, 1],
      [7, 2],
      [7, 3],
      [7, 4],
      [8, 2],
    ],
  },
];

export function presetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
